// Real, attributed motivational quotes.
// Curated for discipline, transformation, grit, health, persistence.
// 210 entries — enough for 182 days with no repeat.

export const QUOTES = [
  // ─── Stoicism / Antiquity ───
  { q: "You have power over your mind — not outside events. Realize this, and you will find strength.", a: "Marcus Aurelius" },
  { q: "Waste no more time arguing what a good man should be. Be one.", a: "Marcus Aurelius" },
  { q: "The impediment to action advances action. What stands in the way becomes the way.", a: "Marcus Aurelius" },
  { q: "Begin at once to live, and count each separate day as a separate life.", a: "Seneca" },
  { q: "Every new beginning comes from some other beginning's end.", a: "Seneca" },
  { q: "Luck is what happens when preparation meets opportunity.", a: "Seneca" },
  { q: "Difficulties strengthen the mind, as labor does the body.", a: "Seneca" },
  { q: "We suffer more often in imagination than in reality.", a: "Seneca" },
  { q: "First say to yourself what you would be; and then do what you have to do.", a: "Epictetus" },
  { q: "No man is free who is not master of himself.", a: "Epictetus" },
  { q: "It's not what happens to you, but how you react to it that matters.", a: "Epictetus" },
  { q: "The greater the difficulty, the more glory in surmounting it.", a: "Epicurus" },
  { q: "Know thyself.", a: "Socrates" },
  { q: "The unexamined life is not worth living.", a: "Socrates" },
  { q: "An unexamined life is not worth living. An unchallenged body is not worth having.", a: "Socrates (paraphrase)" },
  { q: "No man has the right to be an amateur in the matter of physical training.", a: "Socrates" },
  { q: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a: "Will Durant (on Aristotle)" },
  { q: "The journey of a thousand miles begins with one step.", a: "Lao Tzu" },
  { q: "A man who conquers himself is greater than one who conquers a thousand men in battle.", a: "Buddha" },
  { q: "To keep the body in good health is a duty — otherwise we shall not be able to keep our mind strong and clear.", a: "Buddha" },
  { q: "He who conquers others is strong; he who conquers himself is mighty.", a: "Lao Tzu" },
  { q: "Nature does not hurry, yet everything is accomplished.", a: "Lao Tzu" },
  { q: "The flame that burns twice as bright burns half as long.", a: "Lao Tzu" },
  { q: "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", a: "Sun Tzu" },
  { q: "In the midst of chaos, there is also opportunity.", a: "Sun Tzu" },

  // ─── Combat sports ───
  { q: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", a: "Muhammad Ali" },
  { q: "Float like a butterfly, sting like a bee.", a: "Muhammad Ali" },
  { q: "It isn't the mountains ahead to climb that wear you out; it's the pebble in your shoe.", a: "Muhammad Ali" },
  { q: "Don't count the days, make the days count.", a: "Muhammad Ali" },
  { q: "The fight is won or lost far away from witnesses — behind the lines, in the gym, and out there on the road, long before I dance under those lights.", a: "Muhammad Ali" },
  { q: "Service to others is the rent you pay for your room here on earth.", a: "Muhammad Ali" },
  { q: "I am the greatest. I said that even before I knew I was.", a: "Muhammad Ali" },
  { q: "Champions aren't made in gyms. Champions are made from something they have deep inside them — a desire, a dream, a vision.", a: "Muhammad Ali" },
  { q: "Do not pray for an easy life. Pray for the strength to endure a difficult one.", a: "Bruce Lee" },
  { q: "Absorb what is useful, discard what is not, add what is uniquely your own.", a: "Bruce Lee" },
  { q: "The successful warrior is the average man, with laser-like focus.", a: "Bruce Lee" },
  { q: "If you spend too much time thinking about a thing, you'll never get it done.", a: "Bruce Lee" },
  { q: "Don't fear failure. Not failure, but low aim, is the crime.", a: "Bruce Lee" },
  { q: "Mistakes are always forgivable, if one has the courage to admit them.", a: "Bruce Lee" },
  { q: "Knowing is not enough; we must apply. Willing is not enough; we must do.", a: "Bruce Lee" },
  { q: "As you think, so shall you become.", a: "Bruce Lee" },
  { q: "Be water, my friend.", a: "Bruce Lee" },
  { q: "Everyone has a plan until they get punched in the mouth.", a: "Mike Tyson" },
  { q: "Discipline is doing what you hate to do, but doing it like you love it.", a: "Mike Tyson" },
  { q: "I'm not the same person I was five minutes ago.", a: "Mike Tyson" },

  // ─── Bodybuilding / Strength ───
  { q: "Everybody wants to be a bodybuilder, but nobody wants to lift no heavy-ass weights.", a: "Ronnie Coleman" },
  { q: "Yeah buddy — light weight, baby.", a: "Ronnie Coleman" },
  { q: "Strength does not come from winning. Your struggles develop your strengths.", a: "Arnold Schwarzenegger" },
  { q: "The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion.", a: "Arnold Schwarzenegger" },
  { q: "The worst thing I can be is the same as everybody else. I hate that.", a: "Arnold Schwarzenegger" },
  { q: "You can't climb the ladder of success with your hands in your pockets.", a: "Arnold Schwarzenegger" },
  { q: "For me, life is continuously being hungry. The meaning of life is not simply to exist, to survive, but to move ahead, to go up, to achieve, to conquer.", a: "Arnold Schwarzenegger" },
  { q: "If you want to turn a vision into reality, you have to give 100 percent and never stop believing in your dream.", a: "Arnold Schwarzenegger" },
  { q: "Stop whining. No one cares.", a: "Arnold Schwarzenegger" },
  { q: "Milk is for babies. When you grow up you have to drink beer.", a: "Arnold Schwarzenegger" },
  { q: "What we fear doing most is usually what we most need to do.", a: "Tim Ferriss" },

  // ─── Modern grit / military ───
  { q: "You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential.", a: "David Goggins" },
  { q: "Most of us give up when we've only given around 40 percent of our maximum effort.", a: "David Goggins" },
  { q: "When you think that you are done, you're only 40 percent in.", a: "David Goggins" },
  { q: "The only way you gain mental toughness is to do things you're not happy doing.", a: "David Goggins" },
  { q: "We live in an external world. Everything is about what you see — the house, the car, the money. The best things are internal.", a: "David Goggins" },
  { q: "Stay hard.", a: "David Goggins" },
  { q: "Be uncommon amongst uncommon people.", a: "David Goggins" },
  { q: "The easy road always leads to nowhere.", a: "David Goggins" },
  { q: "Suffering is the true test of life.", a: "David Goggins" },
  { q: "You have to build calluses on your brain just like how you build calluses on your hands.", a: "David Goggins" },
  { q: "Get some.", a: "Jocko Willink" },
  { q: "Discipline equals freedom.", a: "Jocko Willink" },
  { q: "Good.", a: "Jocko Willink" },
  { q: "The only easy day was yesterday.", a: "Navy SEAL motto" },
  { q: "Under pressure, you don't rise to the occasion, you sink to the level of your training.", a: "Navy SEAL saying" },
  { q: "If you want to change the world, start off by making your bed.", a: "Admiral William H. McRaven" },
  { q: "The more you sweat in peace, the less you bleed in war.", a: "Norman Schwarzkopf" },

  // ─── Basketball legends ───
  { q: "I've failed over and over and over again in my life. And that is why I succeed.", a: "Michael Jordan" },
  { q: "I can accept failure, everyone fails at something. But I can't accept not trying.", a: "Michael Jordan" },
  { q: "Some people want it to happen, some wish it would happen, others make it happen.", a: "Michael Jordan" },
  { q: "Talent wins games, but teamwork and intelligence win championships.", a: "Michael Jordan" },
  { q: "Obstacles don't have to stop you. If you run into a wall, don't turn around and give up. Figure out how to climb it, go through it, or work around it.", a: "Michael Jordan" },
  { q: "If you're afraid of failure, you don't deserve to be successful.", a: "Charles Barkley" },
  { q: "Rest at the end, not in the middle.", a: "Kobe Bryant" },
  { q: "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", a: "Kobe Bryant" },
  { q: "Great things come from hard work and perseverance. No excuses.", a: "Kobe Bryant" },
  { q: "I have self-doubt. I have insecurity. I have fear of failure. We all have self-doubt.", a: "Kobe Bryant" },
  { q: "Everything negative — pressure, challenges — is all an opportunity for me to rise.", a: "Kobe Bryant" },
  { q: "If you want to be great at something, there's a choice you have to make. We can all be masters at our craft, but you have to make a choice.", a: "Kobe Bryant" },
  { q: "Mamba mentality is all about 4 AM workouts, doing more than the next guy.", a: "Kobe Bryant" },
  { q: "The most important part is that your family stays with you. Once you know what it feels like to lose, you'll never want to feel that way again.", a: "Kobe Bryant" },

  // ─── Running / endurance ───
  { q: "Pain is inevitable. Suffering is optional.", a: "Haruki Murakami" },
  { q: "Run when you can, walk if you have to, crawl if you must; just never give up.", a: "Dean Karnazes" },
  { q: "The miracle isn't that I finished. The miracle is that I had the courage to start.", a: "John Bingham" },
  { q: "It does not matter how slowly you go, as long as you do not stop.", a: "Confucius" },
  { q: "Our greatest glory is not in never falling, but in rising every time we fall.", a: "Confucius" },
  { q: "The man who moves a mountain begins by carrying away small stones.", a: "Confucius" },
  { q: "Choose a job you love, and you will never have to work a day in your life.", a: "Confucius" },
  { q: "Somebody may beat me, but they are going to have to bleed to do it.", a: "Steve Prefontaine" },
  { q: "To give anything less than your best is to sacrifice the gift.", a: "Steve Prefontaine" },

  // ─── Philosophy / literature ───
  { q: "That which does not kill us makes us stronger.", a: "Friedrich Nietzsche" },
  { q: "He who has a why to live for can bear almost any how.", a: "Friedrich Nietzsche" },
  { q: "You must have chaos within you to give birth to a dancing star.", a: "Friedrich Nietzsche" },
  { q: "Become who you are.", a: "Friedrich Nietzsche" },
  { q: "The mind is everything. What you think you become.", a: "Buddha" },
  { q: "It is never too late to be what you might have been.", a: "George Eliot" },
  { q: "Do not go where the path may lead, go instead where there is no path and leave a trail.", a: "Ralph Waldo Emerson" },
  { q: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", a: "Ralph Waldo Emerson" },
  { q: "Self-trust is the first secret of success.", a: "Ralph Waldo Emerson" },
  { q: "Make your life a masterpiece; imagine no limitations.", a: "Brian Tracy" },
  { q: "The world breaks everyone, and afterward, many are strong at the broken places.", a: "Ernest Hemingway" },
  { q: "Man is not made for defeat. A man can be destroyed but not defeated.", a: "Ernest Hemingway" },
  { q: "I cannot and will not cut my conscience to fit this year's fashions.", a: "Lillian Hellman" },
  { q: "Whether you think you can, or you think you can't — you're right.", a: "Henry Ford" },
  { q: "Quality means doing it right when no one is looking.", a: "Henry Ford" },
  { q: "The only person you are destined to become is the person you decide to be.", a: "Ralph Waldo Emerson" },

  // ─── Political / historical ───
  { q: "Do what you can, with what you have, where you are.", a: "Theodore Roosevelt" },
  { q: "Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty.", a: "Theodore Roosevelt" },
  { q: "Believe you can and you're halfway there.", a: "Theodore Roosevelt" },
  { q: "It is not the critic who counts; the credit belongs to the man who is actually in the arena.", a: "Theodore Roosevelt" },
  { q: "Success is not final, failure is not fatal: it is the courage to continue that counts.", a: "Winston Churchill" },
  { q: "If you're going through hell, keep going.", a: "Winston Churchill" },
  { q: "Never, never, never give up.", a: "Winston Churchill" },
  { q: "Attitude is a little thing that makes a big difference.", a: "Winston Churchill" },
  { q: "We shall not flag or fail.", a: "Winston Churchill" },
  { q: "Be the change that you wish to see in the world.", a: "Mahatma Gandhi" },
  { q: "Strength does not come from physical capacity. It comes from an indomitable will.", a: "Mahatma Gandhi" },
  { q: "The best way to find yourself is to lose yourself in the service of others.", a: "Mahatma Gandhi" },
  { q: "It always seems impossible until it's done.", a: "Nelson Mandela" },
  { q: "The greatest glory in living lies not in never falling, but in rising every time we fall.", a: "Nelson Mandela" },
  { q: "I learned that courage was not the absence of fear, but the triumph over it.", a: "Nelson Mandela" },
  { q: "Education is the most powerful weapon which you can use to change the world.", a: "Nelson Mandela" },
  { q: "There are no shortcuts to any place worth going.", a: "Beverly Sills" },
  { q: "In the middle of every difficulty lies opportunity.", a: "Albert Einstein" },
  { q: "Strive not to be a success, but rather to be of value.", a: "Albert Einstein" },
  { q: "Life is like riding a bicycle. To keep your balance, you must keep moving.", a: "Albert Einstein" },
  { q: "A person who never made a mistake never tried anything new.", a: "Albert Einstein" },

  // ─── Entrepreneurs / innovators ───
  { q: "The only way to do great work is to love what you do.", a: "Steve Jobs" },
  { q: "Your time is limited, so don't waste it living someone else's life.", a: "Steve Jobs" },
  { q: "Stay hungry. Stay foolish.", a: "Steve Jobs" },
  { q: "Innovation distinguishes between a leader and a follower.", a: "Steve Jobs" },
  { q: "If you are working on something exciting that you really care about, you don't have to be pushed. The vision pulls you.", a: "Steve Jobs" },
  { q: "When something is important enough, you do it even if the odds are not in your favor.", a: "Elon Musk" },
  { q: "Persistence is very important. You should not give up unless you are forced to give up.", a: "Elon Musk" },
  { q: "I think it is possible for ordinary people to choose to be extraordinary.", a: "Elon Musk" },
  { q: "Failure is an option here. If things are not failing, you are not innovating enough.", a: "Elon Musk" },
  { q: "If you're not making mistakes, then you're not making decisions.", a: "Catherine Cook" },

  // ─── Rocky ───
  { q: "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.", a: "Rocky Balboa (Sylvester Stallone)" },
  { q: "Every champion was once a contender that refused to give up.", a: "Rocky Balboa (Sylvester Stallone)" },
  { q: "If I can change, and you can change, everybody can change.", a: "Rocky Balboa (Sylvester Stallone)" },
  { q: "The only respect that matters is self-respect.", a: "Rocky Balboa (Sylvester Stallone)" },

  // ─── Writers / thinkers ───
  { q: "An unwatched pot boils immediately.", a: "H. F. Ellis" },
  { q: "What you do every day matters more than what you do once in a while.", a: "Gretchen Rubin" },
  { q: "You don't have to see the whole staircase, just take the first step.", a: "Martin Luther King Jr." },
  { q: "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.", a: "Martin Luther King Jr." },
  { q: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", a: "Martin Luther King Jr." },
  { q: "In the end, it's not the years in your life that count. It's the life in your years.", a: "Abraham Lincoln" },
  { q: "Discipline is the bridge between goals and accomplishment.", a: "Jim Rohn" },
  { q: "Take care of your body. It's the only place you have to live.", a: "Jim Rohn" },
  { q: "Success is nothing more than a few simple disciplines, practiced every day.", a: "Jim Rohn" },
  { q: "Motivation is what gets you started. Habit is what keeps you going.", a: "Jim Rohn" },
  { q: "Don't wish it were easier. Wish you were better.", a: "Jim Rohn" },
  { q: "Your body hears everything your mind says.", a: "Naomi Judd" },
  { q: "Take care of your body with steadfast fidelity.", a: "Epictetus" },
  { q: "Nothing is impossible. The word itself says 'I'm possible!'", a: "Audrey Hepburn" },
  { q: "You miss 100% of the shots you don't take.", a: "Wayne Gretzky" },
  { q: "Hard work beats talent when talent doesn't work hard.", a: "Tim Notke" },
  { q: "Never let the fear of striking out keep you from playing the game.", a: "Babe Ruth" },
  { q: "It's not whether you get knocked down, it's whether you get up.", a: "Vince Lombardi" },
  { q: "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.", a: "Vince Lombardi" },
  { q: "Perfection is not attainable, but if we chase perfection we can catch excellence.", a: "Vince Lombardi" },
  { q: "Winners never quit and quitters never win.", a: "Vince Lombardi" },
  { q: "The dictionary is the only place that success comes before work.", a: "Vince Lombardi" },

  // ─── Health / longevity ───
  { q: "He who has health has hope; and he who has hope has everything.", a: "Arabian Proverb" },
  { q: "The groundwork for all happiness is good health.", a: "Leigh Hunt" },
  { q: "Let food be thy medicine and medicine be thy food.", a: "Hippocrates" },
  { q: "Walking is man's best medicine.", a: "Hippocrates" },
  { q: "If you are in a bad mood go for a walk. If you are still in a bad mood go for another walk.", a: "Hippocrates" },
  { q: "Physical fitness is the first requisite of happiness.", a: "Joseph Pilates" },
  { q: "Take care of your body. It's the only place you have to live.", a: "Jim Rohn" },
  { q: "The body achieves what the mind believes.", a: "Napoleon Hill" },
  { q: "Whether you think you can or think you can't, you're right.", a: "Henry Ford" },
  { q: "Those who think they have no time for exercise will sooner or later have to find time for illness.", a: "Edward Stanley" },
  { q: "Our bodies are our gardens — our wills are our gardeners.", a: "William Shakespeare" },
  { q: "Fitness is not about being better than someone else. It's about being better than you used to be.", a: "Khloé Kardashian" },

  // ─── Writers on action ───
  { q: "An arrow can only be shot by pulling it backward. When life is dragging you back with difficulties, it means it's going to launch you into something great.", a: "Paulo Coelho" },
  { q: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", a: "Dan Millman" },
  { q: "A year from now you may wish you had started today.", a: "Karen Lamb" },
  { q: "Do one thing every day that scares you.", a: "Eleanor Roosevelt" },
  { q: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt" },
  { q: "You gain strength, courage and confidence by every experience in which you really stop to look fear in the face.", a: "Eleanor Roosevelt" },
  { q: "No one can make you feel inferior without your consent.", a: "Eleanor Roosevelt" },
  { q: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.", a: "Mark Twain (attributed)" },
  { q: "The secret of getting ahead is getting started.", a: "Mark Twain" },
  { q: "Don't say you don't have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein.", a: "H. Jackson Brown Jr." },

  // ─── Writers on persistence ───
  { q: "Energy and persistence conquer all things.", a: "Benjamin Franklin" },
  { q: "Either write something worth reading or do something worth writing.", a: "Benjamin Franklin" },
  { q: "By failing to prepare, you are preparing to fail.", a: "Benjamin Franklin" },
  { q: "Lost time is never found again.", a: "Benjamin Franklin" },
  { q: "An ounce of prevention is worth a pound of cure.", a: "Benjamin Franklin" },
  { q: "Well done is better than well said.", a: "Benjamin Franklin" },
  { q: "Don't watch the clock; do what it does. Keep going.", a: "Sam Levenson" },
  { q: "Fall seven times, stand up eight.", a: "Japanese Proverb" },
  { q: "A jug fills drop by drop.", a: "Buddha" },
  { q: "The best time to plant a tree was 20 years ago. The second best time is now.", a: "Chinese Proverb" },
  { q: "A smooth sea never made a skilled sailor.", a: "Franklin D. Roosevelt" },

  // ─── Discipline / self-mastery ───
  { q: "Rule your mind or it will rule you.", a: "Horace" },
  { q: "We don't rise to the level of our expectations, we fall to the level of our training.", a: "Archilochus" },
  { q: "Temper is the one thing you can't get rid of by losing it.", a: "Jack Nicklaus" },
  { q: "He who has overcome his fears will truly be free.", a: "Aristotle" },
  { q: "Patience is bitter, but its fruit is sweet.", a: "Aristotle" },
  { q: "We cannot solve our problems with the same thinking we used when we created them.", a: "Albert Einstein" },
  { q: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", a: "Alan Watts" },
  { q: "The more I practice, the luckier I get.", a: "Gary Player" },

  // ─── Modern extras ───
  { q: "Only those who dare to fail greatly can ever achieve greatly.", a: "Robert F. Kennedy" },
  { q: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", a: "Thomas Edison" },
  { q: "Genius is one percent inspiration and ninety-nine percent perspiration.", a: "Thomas Edison" },
  { q: "I have not failed. I've just found 10,000 ways that won't work.", a: "Thomas Edison" },
  { q: "The difference between ordinary and extraordinary is that little extra.", a: "Jimmy Johnson" },
  { q: "The body benefits from movement, and the mind benefits from stillness.", a: "Sakyong Mipham" },
  { q: "To enjoy the glow of good health, you must exercise.", a: "Gene Tunney" },
  { q: "If it doesn't challenge you, it won't change you.", a: "Fred DeVito" },
  { q: "The pain you feel today will be the strength you feel tomorrow.", a: "Arnold Schwarzenegger (attributed)" },
  { q: "Don't limit your challenges. Challenge your limits.", a: "Jerry Dunn" },
  { q: "Sweat is fat crying.", a: "Common gym saying" },
  { q: "If you don't find time for exercise, you'll have to find time for illness.", a: "Robin Sharma" },

  // ─── Extras to hit 210 ───
  { q: "Start where you are. Use what you have. Do what you can.", a: "Arthur Ashe" },
  { q: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing.", a: "Pelé" },
  { q: "The best revenge is massive success.", a: "Frank Sinatra" },
  { q: "Don't let yesterday take up too much of today.", a: "Will Rogers" },
  { q: "Go confidently in the direction of your dreams. Live the life you have imagined.", a: "Henry David Thoreau" },
  { q: "What you get by achieving your goals is not as important as what you become by achieving your goals.", a: "Zig Ziglar" },
  { q: "You don't have to be great to start, but you have to start to be great.", a: "Zig Ziglar" },
  { q: "People often say that motivation doesn't last. Well, neither does bathing — that's why we recommend it daily.", a: "Zig Ziglar" },
  { q: "Your attitude, not your aptitude, will determine your altitude.", a: "Zig Ziglar" },
  { q: "When obstacles arise, you change your direction to reach your goal; you do not change your decision to get there.", a: "Zig Ziglar" }
];

// ─── Pickers ───

// Simple string hash — djb2-ish
const hash = (s) => {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
  return Math.abs(h);
};

export const quoteForDate = (dateStr) => QUOTES[hash(dateStr) % QUOTES.length];

export const randomQuote = () => QUOTES[Math.floor(Math.random() * QUOTES.length)];
